import { NlpEntity } from 'components/types';

export const mockEntities: NlpEntity[] = [
  {
    id: 0,
    matchingTokens: [1],
    entityId: 'Hygiene',
    confidenceScore: 1.306,
    wikiLink: 'http://en.wikipedia.org/wiki/Hygiene',
    matchedText: 'hygiene',
    freebaseId: '/m/012sj0',
    relevanceScore: 0.01721,
    entityEnglishId: 'Hygiene',
    startingPos: 4,
    endingPos: 11,
    wikidataId: 'Q162297',
  },
  {
    id: 1,
    type: ['Place', 'PopulatedPlace', 'Country'],
    matchingTokens: [14],
    entityId: 'Sweden',
    confidenceScore: 3.516,
    wikiLink: 'http://en.wikipedia.org/wiki/Sweden',
    matchedText: 'Sweden',
    freebaseId: '/m/0d0vqn',
    relevanceScore: 0.01114,
    entityEnglishId: 'Sweden',
    startingPos: 81,
    endingPos: 87,
    wikidataId: 'Q34',
  },
  {
    id: 2,
    type: ['Country'],
    matchingTokens: [14],
    entityId: 'Finland',
    confidenceScore: 4.916,
    wikiLink: 'http://en.wikipedia.org/wiki/Finland',
    matchedText: 'Finland',
    freebaseId: '/m/0d0vqn',
    relevanceScore: 0.25114,
    entityEnglishId: 'Finland',
    startingPos: 81,
    endingPos: 87,
    wikidataId: 'Q3477',
  },
];
